//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TVShows.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TVShows.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TV Shows.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ← Back.
        /// </summary>
        public static string BackWithSymbol {
            get {
                return ResourceManager.GetString("BackWithSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date:.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading image.
        /// </summary>
        public static string ErrorLoadingImage {
            get {
                return ResourceManager.GetString("ErrorLoadingImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite Shows.
        /// </summary>
        public static string FavoriteShows {
            get {
                return ResourceManager.GetString("FavoriteShows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading favorites....
        /// </summary>
        public static string LoadingFavorites {
            get {
                return ResourceManager.GetString("LoadingFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading more shows....
        /// </summary>
        public static string LoadingMoreShows {
            get {
                return ResourceManager.GetString("LoadingMoreShows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading recently viewed shows....
        /// </summary>
        public static string LoadingRecentlyViewedShows {
            get {
                return ResourceManager.GetString("LoadingRecentlyViewedShows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading shows....
        /// </summary>
        public static string LoadingShows {
            get {
                return ResourceManager.GetString("LoadingShows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t added any favorite shows yet..
        /// </summary>
        public static string NoFavoritesAdded {
            get {
                return ResourceManager.GetString("NoFavoritesAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No image available.
        /// </summary>
        public static string NoImageAvaliable {
            get {
                return ResourceManager.GetString("NoImageAvaliable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No more shows available.
        /// </summary>
        public static string NoMoreShows {
            get {
                return ResourceManager.GetString("NoMoreShows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t viewed any shows yet..
        /// </summary>
        public static string NoRecentlyViewedShows {
            get {
                return ResourceManager.GetString("NoRecentlyViewedShows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The last 50 shows you&apos;ve viewed will appear here..
        /// </summary>
        public static string NoRecentlyViewedShowsHint {
            get {
                return ResourceManager.GetString("NoRecentlyViewedShowsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No TV show found named &quot;{0}&quot;.
        /// </summary>
        public static string NoShowFoundBySearch {
            get {
                return ResourceManager.GetString("NoShowFoundBySearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No TV shows found..
        /// </summary>
        public static string NoShowsFound {
            get {
                return ResourceManager.GetString("NoShowsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premiere date:.
        /// </summary>
        public static string PremiereDate {
            get {
                return ResourceManager.GetString("PremiereDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recently Viewed Shows.
        /// </summary>
        public static string RecentlyViewedShows {
            get {
                return ResourceManager.GetString("RecentlyViewedShows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recents.
        /// </summary>
        public static string Recents {
            get {
                return ResourceManager.GetString("Recents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from recently viewed.
        /// </summary>
        public static string RemoveRecentlyViewedShow {
            get {
                return ResourceManager.GetString("RemoveRecentlyViewedShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for &quot;{0}&quot;....
        /// </summary>
        public static string SearchingFor {
            get {
                return ResourceManager.GetString("SearchingFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Season.
        /// </summary>
        public static string Season {
            get {
                return ResourceManager.GetString("Season", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seasons.
        /// </summary>
        public static string Seasons {
            get {
                return ResourceManager.GetString("Seasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  | Details.
        /// </summary>
        public static string ShowDetails {
            get {
                return ResourceManager.GetString("ShowDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type to search....
        /// </summary>
        public static string TypeToSearch {
            get {
                return ResourceManager.GetString("TypeToSearch", resourceCulture);
            }
        }
    }
}
